server:
  host:
    mariadb: 127.0.0.1
  port: 9080
  error:
    include-exception: false      # Response ? Exception ? ????
    include-message: always       # Response ? Exception Message ? ???? (never | always | on_param)
    include-stacktrace: on_param  # Response ? Stack Trace ? ???? (never | always | on_param) on_trace_params ? deprecated
    whitelabel.enabled: true      # ?? ?? ? Spring ?? ?? ??? ?? ??

spring:
  application:
    name: viewer
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/mo2ver_dev
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG
        security: DEBUG
        web:
          filter: DEBUG

crypto-setting:
  password: mo2ver_aes256cbc_pbkdf2
  salt: mo2ver_salt

file-setting:
  filepath: ../Mo2ver

oracle:
  cloud:
    tenant-id: ocid1.tenancy.oc1..aaaaaaaa7osy4snfj6wc7zm7fab4njjnmifhlz5e5454gp4km7wlnqhtmtaa
    user-id: ocid1.user.oc1..aaaaaaaaxrysvkqe7xqot26li232sotr4ir7fqbnpexnn2o256f2nk6fanna
    fingerprint: cd:37:53:41:4d:cf:f2:5e:a1:da:83:86:0e:b7:14:95
    namespace: cnocuvkcoanz
    bucket-name: bucket-20231206-2356
    private-key: ./key/mo2ver_bucket_api_key.pem